### ISSUE TITLE
numpy too old and can no longer test with new

### ISSUE THREAD

**Issue by dchmelik** [Mathics3/mathics-core#1151]
**Is your feature request related to a problem? Please describe.**
```
root@darwinheim:~# mathicsserver
/usr/lib64/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.3

```
**Describe the solution you'd like**
Restore/document possibility (setup.py had when editing) to test with any/all new dependencies, or continually update stable versions.

**Describe alternatives you've considered**
Build from git.

**Additional context**
I maintain [mathics SlackBuild](http://slackbuilds.org/repository/15.0/academic/mathics/) so people can build & install Mathics on Slackware GNU/Linux, but don't know I'd update to only use git commits...

**Comment by mmatera** [comment]
@dchmelik, in the current main branch, we support numpy<1.27, so 1.26.3 should be supported. If you want to check mathics against a newer version of numpy, just modify the pyproject.toml file:
https://github.com/Mathics3/mathics-core/blob/a39a3e940c5b087e25002099c3596cc50cd4cbb2/pyproject.toml#L16

**Comment by dchmelik** [comment]
thanks
