### ISSUE TITLE
`CosineDistance[{a, b}, {x, y}]` - x,y values aren't conjugated

### ISSUE THREAD

**Issue by axkr** [Mathics3/mathics-core#1197]
In WMA 14.1.0

```mma
  CosineDistance[{a, b}, {x, y}]
```

returns a result with x,y values conjugated:
```mma
  1 - (a*Conjugate[x] + b*Conjugate[y])/(Sqrt[Abs[a]^2 + Abs[b]^2]*Sqrt[Abs[x]^2 + Abs[y]^2]) 
```

- https://github.com/Mathics3/mathics-core/blob/807bd57f075a109cd790ad10a1365c26fe451306/mathics/builtin/distance/numeric.py#L142

**Comment by rocky** [comment]
I will fix this when I get a chance.  It seems that there are a couple issues with Mathics3 `CosineDistance[]` in addition to this one reported. 

In issue that also appears in Symja is the fact that the lengths of the two vectors are not checked for length equality.

**Comment by rocky** [comment]
@axkr #1199 will probalby address this. I culled code from https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/ClusteringFunctions.java#L377-L386 . However, I note that Symja  does not seem to handle situations where the arguments are numeric scalars, so you might want to copy back from #1199. 

For scalar numeric arguments, it appears that what one does is use `Abs[]` for `Norm[]`, and `Times[]` for `Dot[]`. 

The distance module in Symja,  generally  looks a little better organized (better thought out in more general distance-like terms) than Mathics3. Mathics3 should be on the lookout for opportunities where we can improve organization following code in Symja.
