### ISSUE TITLE
Option to disable autoclose of parentheses

### ISSUE THREAD

**Issue by DUOLabs333** [Mathics3/mathics-core#151]
Is there an option to disable Mathics autoclosing parentheses?

**Comment by rocky** [comment]
The command-line utility, called `mathics` in this repo doesn't have auto-closing parenthesis.  The only command-line utility that I know of is the one provided by [mathicsscript](https://github.com/Mathics3/mathicsscript).

And even there, it is only the default readline that does this. So if you run mathicsscript with `--readline GNU` or `--readline None` this will disable this aspect. It changes other things as well. 

If you are looking a setting that disables this and nothing else, the answer is no: there's no setting. Feel free to change the code and put in a PR.

**Comment by DUOLabs333** [comment]
Where does the code for the default readline located?

**Comment by rocky** [comment]
Open this issue in mathicsscript and I'll respond there. This isn't a mathics core issue.
