### ISSUE TITLE
Solve[f(x,y,z),z] doesn't solve for z

### ISSUE THREAD

**Issue by DUOLabs333** [Mathics3/mathics-core#152]
If I have a function of two or three variables, using Solve[f,z] doesn't work to solve for z -- for example, `Solve[2000==2(yz+xy+xz)-xy,z]`

**Comment by DUOLabs333** [comment]
Apparently, you needed to but `*` between each of the variables.

**Comment by rocky** [comment]
Yes, this is a basic aspect of WL/Mathics. while `2y` means "2 times x", `xy` is the variable `xy` and `x2` is also a variable `x2`.
