### ISSUE TITLE
Double integration with `f(x,y)=1` fails, while any other constant succeeds

### ISSUE THREAD

**Issue by DUOLabs333** [Mathics3/mathics-core#153]
`Integrate[Integrate[1,{y,0,E^x}],{x,0,Log[13]}]` gives `Integrate[ConditionalExpression[E, {True}], {x, 0, Log[13]}]` when `Integrate[Integrate[2,{y,0,E^x}],{x,0,Log[13]}]` or `Integrate[Integrate[0,{y,0,E^x}],{x,0,Log[13]}]` or even `Integrate[Integrate[0.9999999,{y,0,E^x}],{x,0,Log[13]}]` works.

**Comment by DUOLabs333** [comment]
Using `1.0` succeeds.

**Comment by DUOLabs333** [comment]
Sympy does not have this issue.

**Comment by DUOLabs333** [comment]
Interestingly enough, doing `Integrate[1,{y,0,E^x-1}]` works.

**Comment by rocky** [comment]
I suppose you add some debug statements to see what 1.0 sends to SymPy and compare that with what happens now.

Personally, this is not something I am interested in or going to look at, unless there is a good reason to.

I have more than enough other things to that are more pressing.

**Comment by DUOLabs333** [comment]
Interestingly, `result` in `sympy.integrate(f_sympy, *vars)` gives the right answer.

**Comment by DUOLabs333** [comment]
Commenting out `result = Expression("Simplify", result, assuming).evaluate(evaluation)` solves this, as well as #154

**Comment by DUOLabs333** [comment]
I think it's because of this `assuming = options["System`Assumptions"].evaluate(evaluation)`

**Comment by DUOLabs333** [comment]
Is it supposed to be supposed to be set to something?

**Comment by DUOLabs333** [comment]
Where is `Simplify` defined? I'm assuming it's some problem with the assumptions.

**Comment by rocky** [comment]
This looks like the commit for that line https://github.com/Mathics3/mathics-core/commit/417f4788e2b081505587cfd2c0343950b6197b60

**Comment by mmatera** [comment]
> Commenting out `result = Expression("Simplify", result, assuming).evaluate(evaluation)` solves this, as well as #154

I guess that a better approach to solve this would be to add a rule
``ConditionalExpression[val_,{True}]->val``
in ``ConditionalExpression``

**Comment by DUOLabs333** [comment]
Or maybe return early in Simplify if assumptions are True?

**Comment by mmatera** [comment]
The problem is that Simplify could do some simplifications even if there are no assumtions.

**Comment by DUOLabs333** [comment]
For #154, Simplify shouldn't take that long, that removing makes the evaluation almost instantly?

**Comment by DUOLabs333** [comment]
Does #158 also fix the result of the integral? I get `ConditionalExpression[E, {True}]`, when it should be `ConditionalExpression[E^x, {True}]`

**Comment by rocky** [comment]
I notice that you tend to ask questions that you probably may be able to answer yourself. I imagine you could pull the code from the PR and check whether this is the case. 

Also questions of the form where is a something defined feels like someone who know Python and grep (or ripgrep or git grep or uses a system like uses Microsoft's LSP, e.g. Visual Studio) would be able to answer.

I suppose it is fine to ask to see of others can answer those questions that a little more digging on your own might solve. But should help not be forthcoming, I have noticed that it _is_ possible your you to answer some of these kinds of questions.

**Comment by mmatera** [comment]
> Does #158 also fix the result of the integral? I get `ConditionalExpression[E, {True}]`, when it should be `ConditionalExpression[E^x, {True}]`

Exactly, #158 produces the right answer. The problem is that ``Simplify`` produced  ``ConditionalExpression[E^x, {True}]`` instead of ``ConditionalExpression[E^x, True]``, which evaluates to  ``E^x``.

**Comment by mmatera** [comment]
> I notice that you tend to ask questions that you probably may be able to answer yourself. I imagine you could pull the code from the PR and check whether this is the case.
> 
> Also questions of the form where is a something defined feels like someone who knows Python and grep (or ripgrep or git grep or uses a system like uses Microsoft's LSP, e.g. Visual Studio) would be able to answer.
> 
> I suppose it is fine to ask to see of others can answer those questions that a little more digging on your own might solve. But should help not be forthcoming, I have noticed that it _is_ possible for you to answer some of these kinds of questions.

Another way to answer this would be: if you want to find where a certain builtin symbol is defined, just type in your terminal
```
grep -R "class [TheBuiltinSymbolYouAreLookingFor]" .
```
in the mathics-core folder.

**Comment by DUOLabs333** [comment]
I just pulled from git and it worked! Thanks.
