### ISSUE TITLE
`Reduce` not implemented

### ISSUE THREAD

**Issue by DUOLabs333** [Mathics3/mathics-core#171]
`Reduce[24.0-2x-x^2>0,x,Reals]` just returns `Reduce[24.0-2x-x^2>0,x,Reals]`.

**Comment by TiagoCavalcante** [comment]
That is because we don't have a Reduce function :upside_down_face:. Would you like to add it in a PR?

**Comment by DUOLabs333** [comment]
I'm not too sure -- I don't have Mathematica to check for Compatibility.

**Comment by rocky** [comment]
That's funny - neither do I. Yet, I somehow manage to work on the project.

**Comment by mmatera** [comment]
> I'm not too sure -- I don't have Mathematica to check for Compatibility.

Just look at wolfram reference: https://reference.wolfram.com/language/ref/Reduce.html and try to reproduce the examples :)

**Comment by mmatera** [comment]
In any case, these kinds of functions are not easy to implement from scratch. Probably the best is to look into sympy.

**Comment by DUOLabs333** [comment]
Ok, I have an idea -- if it is an equation, use Solve, but if it is an inequality, use sympy.

**Comment by DUOLabs333** [comment]
Are there any functions defined that help convert expressions into sympy expressions?

**Comment by DUOLabs333** [comment]
Is there any documentation for the codebase (what functions should be defined for each command, how each Command should be structured, etc.)

**Comment by mmatera** [comment]
> Are there any functions defined that help convert expressions into sympy expressions?

``Expression`` has a method ``to_sympy``.

**Comment by DUOLabs333** [comment]
I'm not sure if Mathematica supports Solve with inequalities -- if it does, it may make more sense to extend Solve.

**Comment by DUOLabs333** [comment]
In any case, I have my work cut out for me.

**Comment by mmatera** [comment]
https://reference.wolfram.com/language/ref/Solve.html

**Comment by mmatera** [comment]
This could be useful too: https://docs.sympy.org/latest/modules/solvers/inequalities.html

**Comment by DUOLabs333** [comment]
Ok, so it makes more sense to add to Solve, and maybe Reduce could be a wrapper, specifying domain.

**Comment by DUOLabs333** [comment]
How would you combine a string like `>=` with `left.to_sympy()`.

**Comment by DUOLabs333** [comment]
Ok, got something that works -- took surprisingly very little time.

**Comment by mmatera** [comment]
@DUOLabs333, why did you close this?
