### ISSUE TITLE
Cannot Plot with mathics and mathicsscript

### ISSUE THREAD

**Issue by adamantinum** [Mathics3/mathics-core#182]
Hi,
I'm not able to plot anything with mathics and mathicsscript.
e.g.
```
In[1]:= Plot[Sin[x], {x, 0, \[Pi]}]
Out[1]:= System`Graphics
```
Using Mathics-Django, plotting works.
Is this a common issue or did I need some additional dependency?
Thank you in advance.

**Comment by TiagoCavalcante** [comment]
@adamantinum it should work if you have Asymptote installed.

**Comment by mmatera** [comment]
@TiagoCavalcante, @adamantinum, no: with asymptote, you can export the plot, but not to show the plot. Currently, the text interface does not support to show graphics. pymathics-matplotlib and pymathics-asymptote are packages that (when finished) are going to support that functionality.

**Comment by TiagoCavalcante** [comment]
@mmatera oh, that is why I couldn't make this works with Alpine :laugh;

**Comment by adamantinum** [comment]
Thank you for your answer, I'm going to close this issue.

**Comment by mmatera** [comment]
Maybe we should keep this open: In any case, is something that is in the agenda, as soon as we finish with the core refactor.

**Comment by rocky** [comment]
Actually this broke a while ago. I noticed in the docker container images. As a workaround if you go back docker images like the last stable release 4.0.0, I think it is fixed in there. 

You could probably do something like a git bisect of the docker images to pinpoint where this stopped working within the last 7 months to find where this stopped working. 

I had been meaning to look at this last week but there was so much _other_ activity that I neither looked let alone did a docker release.

**Comment by adamantinum** [comment]
> Actually this broke a while ago. I noticed in the docker container images. As a workaround if you go back docker images like the last stable release 4.0.0, I think it is fixed in there.
> 
> You could probably do something like a git bisect of the docker images to pinpoint where within the last 7 months to find this stopped working.
> 
> I had been meaning to look at this last week but there was so much _other_ activity that I neither looked let alone did a docker release.

Well, with docker, following the steps on the website, it seems broken there too.

**Comment by rocky** [comment]
> 
> Well, with docker, following the steps on the website, it seems broken there too.

I am not totally certain which instructions you are referring to. (Often when I encounter something like this, I'll just ignore the comment and move onto some other task I have in a long line of things to do.)

```
MATHICS_IMAGE=mathicsorg/mathics:4.0.0 dmathicsscript
```

worked for me. If this doesn't do it for you, I suggest just wait until someone gets around to fixing.

**Comment by adamantinum** [comment]
Yes I did in this way.
In the doubt I reinstalled mathics at all. Now 2D plots on mathicsscript work (but not just on mathics), but 3D plots don't.
Thanks, I'll wait for next releases.

**Comment by rocky** [comment]
> > Actually this broke a while ago. I noticed in the docker container images. As a workaround if you go back docker images like the last stable release 4.0.0, I think it is fixed in there.
> > You could probably do something like a git bisect of the docker images to pinpoint where within the last 7 months to find this stopped working.
> > I had been meaning to look at this last week but there was so much _other_ activity that I neither looked let alone did a docker release.
> 
> Well, with docker, following the steps on the website, it seems broken there too.

I just put out [another docker update](https://hub.docker.com/r/mathicsorg/mathics) which fixes this at least under Ubuntu. 

Getting display to work from inside docker can be OS specific so depending on the OS there may need additional fiddling. 

If you want to get this to work locally, use Asymptote 2.78 (the most recent version 2.79) has problems, and even there I had to configure using `--disable-lsp` or I would get a C++ compile error about accessing some member of a structure that doesn't exist.

**Comment by adamantinum** [comment]
> 

Thank you very much, so I guess the problem is that my system has Asymptote 2.70, I'll try as you said.
