### ISSUE TITLE
Hangs with `Integrate[Integrate[1,{x,-Sqrt[r^2-y^2],Sqrt[r^2-y^2]}],{y,-r,r}]`

### ISSUE THREAD

**Issue by DUOLabs333** [Mathics3/mathics-core#190]
Mathics hangs when computing `Integrate[Integrate[1,{x,-Sqrt[r^2-y^2],Sqrt[r^2-y^2]}],{y,-r,r}]`. It never exits.

**Comment by DUOLabs333** [comment]
To be fair, it also fails with sympy directly.

**Comment by rocky** [comment]
@DUOLabs333  I would it greatly if you would investigate and narrow before reporting. Thanks.
