### ISSUE TITLE
Bug in Clear[]? 

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-core#194]
A mentioned in https://github.com/Mathics3/mathics-core/pull/193#issuecomment-1065966814, we might have a bug in `Clear[]`

In WMA: 
```
In[1]:={a+b, Unprotect[Plus];Plus=Q;p+q, Clear[Plus]; r+s} 
Out[1]={Q[a, b], Q[p, q], r + s}`
```

In Mathics, the output is: 

```
Out[1]= {a + b, Q[p, q], r + s}
```

**Comment by mmatera** [comment]
Solved by #195
