### ISSUE TITLE
Crash when matching blank followed by brackets

### ISSUE THREAD

**Issue by hrueter** [Mathics3/mathics-core#203]
### Observed behavior
Mathics crashes when matching against a pattern consisting of a blank followed by square brackets
```
In[1]:= g[i] /. _[i] :> a
```
### Expected behavior as in Mathematica
```
In[1]:= g[i] /. _[i] :> a
Out[1]= a
```
### Possible Work-around
Prefixing the underscore works as expected: `g[i] /. v_[i] :> a`
### Setup
Linux Mint 20.3
Mathics 4.0.0 on CPython 3.8.10 (default, Nov 26 2021, 20:14:08)  using SymPy 1.8, mpmath 1.2.1, numpy 1.17.4

**Comment by TiagoCavalcante** [comment]
Fixed with PR #208.
