### ISSUE TITLE
Assignment of N makes Mathics crash

### ISSUE THREAD

**Issue by adamantinum** [Mathics3/mathics-core#210]
Assignments such as `N = 1` make Mathics crash because lhs has no attribute leaves (file mathics/builtin/assignments/internals.py, line 399)

I don't know if it be better to add an hasattr, as below, or a try-catch.
Obviously it could be useful call the rejected_because_protected function.
```
def process_assign_n(self, lhs, rhs, evaluation, tags, upset):    
    lhs, condition = unroll_conditions(lhs)    
    lhs, rhs = unroll_patterns(lhs, rhs, evaluation)    
    defs = evaluation.definitions    
                              
    if hasattr(lhs, "leaves"):                 # <--- here
        if len(lhs.leaves) not in (1, 2):    
            evaluation.message_args("N", len(lhs.leaves), 1, 2)    
            raise AssignmentException(lhs, None)    
        if len(lhs.leaves) == 1:    
            nprec = SymbolMachinePrecision    
        else:                 
            nprec = lhs.leaves[1]        
        focus = lhs.leaves[0]    
        lhs = Expression(SymbolN, focus, nprec)    
        tags = process_tags_and_upset_dont_allow_custom(    
            tags, upset, self, lhs, focus, evaluation    
        )                     
        count = 0             
        lhs, rhs = process_rhs_conditions(lhs, rhs, condition, evaluation)      
        rule = Rule(lhs, rhs)    
        for tag in tags:      
            if rejected_because_protected(self, lhs, tag, evaluation):    
                continue      
            count += 1        
            defs.add_nvalue(tag, rule)    
        return count > 0 
```

**Comment by rocky** [comment]
From a pure programming standpoint, you don't add `try` unless the access where the error is being called is out of your control and breaks modularity. 

It sounds like a good high-level solution is something more along the lines about checking whether the lhs is a protected function as you observe rather than a more low-level solution about whether some sort of element is compound or not.

**Comment by TiagoCavalcante** [comment]
@adamantinum I'm not sure if that makes sense, if I understand correctly this is happening with only special symbols, and they really shouldn't be re-assigned because the core of Mathics uses them, for example, any type of graphics would not work without N, it is kinda like if Python allowed `def = 1`.

**Comment by adamantinum** [comment]
> > > @adamantinum I'm not sure if that makes sense, if I understand correctly this is happening with only special symbols, and they really shouldn't be re-assigned because the core of Mathics uses them, for example, any type of graphics would not work without N, it is kinda like if Python allowed `def = 1`.
> > 
> > 
> > As far as I tried it happens only with N, if I run e.g. `If=1` I get correctly "Set::wrsym: Symbol If is Protected." To get the same result with `N` I had to comment all lines which call leaves attribute. I don't know the difference in implementation, but initializing leaves would do the job (despite it be an ugly workaround)
> 
> @adamantinum with "do the job" it lets the user assign or show the warning? Anyway, if you could make a PR to we test, that'd be great.
> 
> @rocky @mmatera this is showing that something is really wrong, N should be like any symbol. I don't know even the place to look for this, do you have an idea?

It means it returns the warning N is a protected symbol, as it does for any other Mathics symbol.
I'll try to make a PR, after I'll have understood how leaves attribute works and is defined

**Comment by mmatera** [comment]
I am working on it.  I hope to have it later today.

**Comment by TiagoCavalcante** [comment]
@adamantinum yes, three is buy it isn't that complete, anyway that isn't necessary as mmatera fixed it.

**Comment by adamantinum** [comment]
> @adamantinum yes, there is buy it isn't that complete, anyway that isn't necessary as mmatera fixed it.

Yes, I've seen the PR.
I'm interested in the manual mostly regarding future contributions.
