### ISSUE TITLE
Does  Mathics `Unequal[]` equal WL `Unequal[]`?

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-core#216]
In going over the docs something I noticed. In Mathics `Unequal[] == True` 

We also write `For any expression x and y, Unequal[x, y] == Not[Equal[x, y]]`   And when there are zero or one parameter, our behavior is not _inconsistent_.

But is this correct? That is, in the degenerate situations `Unequal[x] == Equal[x]` ?

**Comment by mmatera** [comment]
In WMA,
```
In[1]:= Unequal[]                                                             
Out[1]= True

In[2]:= Unequal[x]                                           
Out[2]= True

In[3]:= Unequal[x] == Equal[x]
Out[3]= True

```

**Comment by mmatera** [comment]
The inconsistency would be
```
Not[Equal[]] != Unequal[]
```
but this is evaluated to ``True`` in WL...

**Comment by rocky** [comment]
One may consider this an inconsistency, but the Mathics doc careful works around that by specifying parameters when it mentions that.

@mmatera thanks, as always, for checking.
