### ISSUE TITLE
[Feature] `ToExpression[TeXForm]` 

### ISSUE THREAD

**Issue by DUOLabs333** [Mathics3/mathics-core#244]
There's `sympy.parsing.latex.parse_latex`, but it requires the antlr4 python package.

**Comment by mmatera** [comment]
This is actually a good idea. Maybe this is can be implemented as a pymathics module, to avoid add more dependencies in the core

**Comment by rocky** [comment]
While I would like formatting to be extensible on the outside, I don't think it a good idea until boxing and formatting have been gone over. And even then, I think someone with more knowledge of this would have to do something like this as an example and then have it documented in the developers guide

Except in rare cases where a person is already proficient in programming and design systems and understand Mathematica already, I would not encourage, just hacking together something, as has been too many times in this project.

If you want to do this in a private branch for your own personal use, by all means go at it! You will probably learn something in the process.

**Comment by mmatera** [comment]
I think that in that process, we also can learn something about how to deal with interoperability with external modules, this is why I suggest this. In any case, the problem of parsing TeX and producing a Wolfram expression, even if it is based on the current Sympy code, is a big project in itself.

**Comment by DUOLabs333** [comment]
> If you want to do this in a private branch for your own personal use, by all means go at it! You will probably learn something in the process.

I already have, and you're right --- if my past attempts has been any indication, it will probably fail for some input. But it works for me.

**Comment by rocky** [comment]
> > If you want to do this in a private branch for your own personal use, by all means go at it! You will probably learn something in the process.
> 
> I already have, and you're right --- if my past attempts has been any indication, it will probably fail for some input. But it works for me.

Great. Those that are interested in this can go over and look at your repository and try it out. If it turns out there is widespread interest in this and what you have works well, we can consider merging it in here after Boxing and Formatting has been gone over.
