### ISSUE TITLE
Mathics seems to change 1/expr result to expr for some integrals

### ISSUE THREAD

**Issue by nasser1** [Mathics3/mathics-core#346]
I do not know if this has been reported before or not. Please feel free to delete this if this is known issues.

I noticed on some results from Integrate that Mathics return `expr` instead of `1/expr`  by comparing to what `sympy` gives.

The following are just 2 examples, but there are more. 

**Example 1**

```
Mathics 4.0.0
on CPython 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
using SymPy 1.10.1, mpmath 1.2.1, numpy 1.22.4


In[1]:= Integrate[Sec[x]*Tan[x],x]
Out[1]= ConditionalExpression[Cos[x], {Cos[x] != 0}]

```

Compare to 

```
>python
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x=symbols('x')
>>> integrate(sec(x)*tan(x),x)
1/cos(x)


```
**Example 2**

```
In[2]:= Integrate[Sin[x]/(3 + Cos[x])^2,x]
Out[2]= ConditionalExpression[3 + Cos[x], {3 + Cos[x] != 0}]

```

Compare to 

```
>>> integrate(sin(x)/(3 + cos(x))**2,x)
1/(cos(x) + 3)


```

All on Linux Ubuntu 22.04

**Comment by rocky** [comment]
I am seeing the correct result in the current master on github:

```mathematica
In[1]:= Integrate[Sec[x]*Tan[x],x]
Out[1]= 1 / Cos[x]

In[2]:= Integrate[Sin[x]/(3 + Cos[x])^2,x]
Out[2]= 1 / (3 + Cos[x])
```

The bug might be listed in https://github.com/Mathics3/mathics-core/blob/master/CHANGES.rst

If it is not, we should add it to the list of bugs fixed.

**Comment by mmatera** [comment]
I didn't see this bug in my system. Would be a Python 3.10.4 issue?

**Comment by mmatera** [comment]
#461 seems to show that the issue is not there anymore.
