### ISSUE TITLE
Can't load calculus because a dependency on llvmlite

### ISSUE THREAD

**Issue by DUOLabs333** [Mathics3/mathics-core#444]
## Description
     If I run mathicsscript, I get
```
No module named 'llvmlite'
    Not able to load calculus. Check your installation.
```

## How to Reproduce
For CLI:
1. Run mathicsscript

## Output Given

```
No module named 'llvmlite'
    Not able to load calculus. Check your installation.
```

## Expected behavior

It works.

**Comment by DUOLabs333** [comment]
This is because `calculus` depends on `from mathics.core.convert.function`, which depends on `mathics.builtin.compile.types`, which in turn depends on llvmlite.

**Comment by rocky** [comment]
I see almost none of the above information requested. filled out.

**Comment by DUOLabs333** [comment]
Sorry, forgot to remove the comment out lines.

**Comment by rocky** [comment]
Come back when you lean how to follow instructions.

**Comment by rocky** [comment]
Come back when you lean how to follow instructions.

**Comment by DUOLabs333** [comment]
To fix it, I just moved `from mathics.builtin.compile.types import int_type, real_type, bool_type` to the `try` statement.
