### ISSUE TITLE
Exception raised in `elements.sort()` when Image is multiplied by a number

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-core#446]
## Description

In Mathics, an arithmetic expression like times on an  Image causes an exception.

## How to Reproduce

```
$ mathics -e 'Import["ExampleData/Einstein.jpg"] * 5 '  
```

## Output Given

```
Traceback (most recent call last):
  File "/tmp/.pyenv/versions/pyston-2.3.4/bin/mathics", line 33, in <module>
    sys.exit(load_entry_point('Mathics3', 'console_scripts', 'mathics')())
  File "/tmp/Mathics3/mathics-core/mathics/main.py", line 444, in main
    result = evaluation.evaluate(query, timeout=settings.TIMEOUT)
  File "/tmp/Mathics3/mathics-core/mathics/core/evaluation.py", line 362, in evaluate
    result = run_with_timeout_and_stack(evaluate, timeout, self)
  File "/tmp/Mathics3/mathics-core/mathics/core/evaluation.py", line 116, in run_with_timeout_and_stack
    return request()
  File "/tmp/Mathics3/mathics-core/mathics/core/evaluation.py", line 335, in evaluate
    self.last_eval = query.evaluate(self)
  File "/tmp/Mathics3/mathics-core/mathics/core/expression.py", line 474, in evaluate
    expr, reevaluate = expr.rewrite_apply_eval_step(evaluation)
  File "/tmp/Mathics3/mathics-core/mathics/core/expression.py", line 1122, in rewrite_apply_eval_step
    new.sort()
  File "/tmp/Mathics3/mathics-core/mathics/core/expression.py", line 1440, in sort
    elements.sort()
  File "/tmp/Mathics3/mathics-core/mathics/core/atoms.py", line 135, in __lt__
    else super().__lt__(other)
  File "/tmp/Mathics3/mathics-core/mathics/core/element.py", line 166, in __lt__
    return self.get_sort_key() < other.get_sort_key()
```

## Expected behavior

For multiplication, according to @mmatera the scalar is applied to each pixel element. (This behavior for black and white I find weird though and I don't know what the _precise_ definition of multiplying a bit value in the range [0,1] by 5 would mean. 

## Your Environment

all environments, current master: commit 1e23fd5744a22491a5815d7862f9c71b9f05d97c

## Additional context

See https://github.com/Mathics3/mathics-core/pull/447#issuecomment-1193324754

**Comment by mmatera** [comment]
@rocky, all the elements should have a get_sort_key method, and hence, be comparable. It seems that in this case, it was not defined properly.

**Comment by rocky** [comment]
If the reason for this is purely to make this code work then this is circular reasoning. My understanding is that there are certain objects or Atoms where there is no natural or logical ordering. Images would be one of those things. Boxes would be another kind of thing.  One could define an ordering but it would be arbitrary. 

Does WMA define an ordering on Boxes and Images? 

If a function can take advantage of something being ordered, that doesn't mean that elements _have_ to be ordered. Here, we would just say, okay you want this ordered but there is no natural ordering so don't bother to create work.

**Comment by mmatera** [comment]
> If the reason for this is purely to make this code work then this is circular reasoning.

No, it is about consistency: every pair of expressions should be able to be arranged in canonical order.

> My understanding is that there are certain objects or Atoms where there is no natural or logical ordering. Images would be one of those things. Boxes would be another kind of thing. One could define an ordering but it would be arbitrary or not really meaningful.

There is not a "natural" but a canonical order: larger images should be ordered after shorter ones.

> 
> Does WMA define an ordering on Boxes and Images?
> 
> If a function can take advantage of something being ordered, that doesn't mean that elements _have_ to be ordered. Here, we would just say, okay you want this ordered but there is no natural ordering so don't bother to create unnecessary work.

**Comment by rocky** [comment]
There should probably be separate ticket(s) for the general sorting problem. This is an area were I expect lots of non-conformance, and it may be something that we may be chasing for quite a while.
