### ISSUE TITLE
Core: Check  Attribute properties on new builtins

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-core#456]
The following new builtins were added since 4.0.0. Below are the Attributes we currently have in 230c34e67cce33107d0525208265897f7aa4826a : 

- [x] ``Beta`` {Listable, NumericFunction, Protected}
- [ ] ``Bernoulli`` {}
- [ ] ``CatalanNumber`` {NumericFunction, Protected}
- [ ] ``CompositeQ`` {Protected}
- [x] ``Diagonal`` {Protected}
- [ ] ``Divisible`` {Protected}
- [ ] ``EulerPhi`` {Listable, NumericFunction, Protected}
- [x] ``$Echo`` {}
- [x] ``FindRoot`` {HoldAll, Protected}
- [x] ``FindMinimum`` {HoldAll, Protected}
- [x] ``FindMaximum`` {HoldAll, Protected}
- [x] ``LogGamma`` {Listable, NumericFunction, Protected}
- [ ] ``ModularInverse`` {NumericFunction, Protected}
- [x] ``NumericFunction`` {Protected}

**Comment by mmatera** [comment]
* `Bernoulli` is called `BernoulliB` in WMA and has attributes `{Listable, Protected}`.
* `CatalanNumber` has attributes `{Listable, NumericFunction, Protected, ReadProtected}`
* `CompositeQ` as attributes `{Listable, Protected}`.
* `Divisible` as attributes `{Listable, Protected, ReadProtected}`
* `EulerPhi` is not `NumericFunction` in WMA.
* `ModularInverse` is not `NumericFunction`.
