### ISSUE TITLE
Missing requirements-cython.txt in release 5.0.0

### ISSUE THREAD

**Issue by vicp74** [Mathics3/mathics-core#483]
File [requirements-cython.txt](https://github.com/Mathics3/mathics-core/blob/master/requirements-cython.txt) is missing in the .tar.gz package for version 5.0.0: [Mathics3-5.0.0.tar.gz](https://github.com/Mathics3/mathics-core/releases/download/5.0.0/Mathics3-5.0.0.tar.gz)

PS: Thanks for this new release! :smiley:

**Comment by rocky** [comment]
Ok - thanks for the information. I will put out a 5.0.1 release when I can, probably at the end of the week. There were a couple of other small changes noticed as well.

**Comment by rocky** [comment]
> Ok - thanks for the information. I will put out a 5.0.1 release when I can, probably at the end of the week. There were a couple of other small changes noticed as well.

Should be in 2526d0a29c7e28ccae99c4cb2ae0bedef22c1a6f in release-5.0.1 branch.

**Comment by rocky** [comment]
@vicp74 I have just released 5.0.2 which should have that file in the tarball now. But please double check. 

Thanks for packing Mathics for AUR. Might I suggest adding https://pypi.org/project/mathicsscript/ and https://pypi.org/project/pymathics-natlang/ as well?

**Comment by vicp74** [comment]
5.0.2 looks good, sorry for the delay.

I hear you suggestion, but I would prefer for someone who used them to upload those packages. In fact, someone else did already upload [mathicsscript](https://aur.archlinux.org/packages/mathicsscript) a few days ago.
