### ISSUE TITLE
Add Undefined in System 

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-core#514]
When mathics starts there is an `Undefined` symbol for it, but it does not appear as in the System context, nor do we have Info on it.

```
$ mathics --full-form

Mathics 5.0.3dev0
.. 
In[1]:= Undefined
Global`Undefined
Out[1]= Undefined

In[2]:= ?Undefined
Out[2]= Null

In[3]:= ??Undefined
Out[3]= Null

In[4]:= Attributes[Undefined]
Out[4]:= {}
```

We expect: 

```
In[1]:= Undefined
System`Undefined
Out[1]:= Undefined

In[2]:= ?? Undefined                                                            

Out[2]= Undefined is a symbol that represents a quantity with no defined value.


        Attributes[Undefined]={Protected}
```

**Comment by rocky** [comment]
Adding this might be a good case study example example for how to add a something of this type. Currently I envision having sections for `KroneckerProduct`,  and `Curl`.

**Comment by mmatera** [comment]
The simpler possibility is to define it as a subclass of `Predefined` and seems to go into `mathics.builtin.numbers.constants` : https://reference.wolfram.com/language/guide/MathematicalConstants.html

Not sure if in sympy there is an equivalent object.

**Comment by rocky** [comment]
> The simpler possibility is to define it as a subclass of `Predefined` and seems to go into `mathics.builtin.numbers.constants` : https://reference.wolfram.com/language/guide/MathematicalConstants.html
> 
> Not sure if in sympy there is an equivalent object.

There was never any requirement that things in `mathics.builtin.numbers.constants` have to be SymPy objects. For example, `Glaisher` is in there and it isn't a SymPy constant.

**Comment by mmatera** [comment]
> > The simpler possibility is to define it as a subclass of `Predefined` and seems to go into `mathics.builtin.numbers.constants` : https://reference.wolfram.com/language/guide/MathematicalConstants.html
> > Not sure if in sympy there is an equivalent object.
> 
> There was never any requirement that things in `mathics.builtin.numbers.constants` have to be SymPy objects. For example, `Glaisher` is in there and it isn't a SymPy constant.

No, it is not a requirement, but if it is, we can take some advantage by using the specific class.
