### ISSUE TITLE
Typo in installation document

### ISSUE THREAD

**Issue by toddmo** [Mathics3/mathics-core#564]
In https://mathics-development-guide.readthedocs.io/en/latest/installing.html,

there's a typo. 

The line 

`$ apt-get install python-dev libsqlite3-devp python-setuptools liblapack-dev llvm-dev`

should be

`$ apt-get install python-dev libsqlite3-dev python-setuptools liblapack-dev llvm-dev`

`libsqlite3-devp` has an extra p

**Comment by mmatera** [comment]
The typo is actually in the [mathics-development-guide](https://github.com/Mathics3/mathics-development-guide) repo.
Fixed in https://github.com/Mathics3/mathics-development-guide/commit/b78cf64240dce56ffe303d3eb5fe14ceab46bcf7
