### ISSUE TITLE
ENABLE_FILES_MODULE flag seems to be ignored

### ISSUE THREAD

**Issue by alek3y** [Mathics3/mathics-core#653]
## Description

Running `mathicsserver` with `ENABLE_FILES_MODULE` set to `False` inside of `mathics/settings.py` seems to not disable the files module properly (for me at least).

## Expected behavior

Commands like
```
CreateFile["test"]
```
shouldn't work when `ENABLE_FILES_MODULE` is false, but instead the file `test` is created anyway.

## Your Environment

The modules involved are:
```
Mathics-Django==5.0.0
Mathics3==5.0.2
```
from either pip or installed manually with `python3 setup.py install` (plus `Mathics-Scanner==1.2.4` but that was installed automatically).

I tried this on Manjaro and inside an Ubuntu Kinetic Docker container, both with Python 3.10.

## Workarounds

Apparently when `subdir` inside `mathics/builtin/__init__.py` is `files_io`, `import_name` is `mathics.builtin.files_io`.

Because this won't match any of the strings inside `disable_file_module_names`, the following code won't prevent the module from being loaded:
```py
if import_name in disable_file_module_names:
        continue
```

I guess this could be fixed by replacing the if statement with:
```py
if subdir in disable_file_module_names:
        continue
```
and setting:
```py
disable_file_module_names = (
    [] if ENABLE_FILES_MODULE else ["files_io"]
)
```
since you probably wouldn't want other functions like `CopyDirectory` either.

**Comment by mmatera** [comment]
@alek3y, this seems to be a side effect of a recent reorganization of the code. If you are up, please implement the fix in a PR. Otherwise, we are going to fix it before the next release.

**Comment by alek3y** [comment]
Yes, that PR seems to work as expected for me, so I think it fixes the issue.

**Comment by rocky** [comment]
Ok - then merging. Thanks for checking, and suggesting and basically fixing.
