### ISSUE TITLE
PyPy not supported

### ISSUE THREAD

**Issue by hyperswine** [Mathics3/mathics-core#661]
## Description

1. Attempting to install `Mathics-omnibus` gets stuck at `Installing build dependencies ... |`.
2. Attempting to install `Mathics3` raises the following error:
```
gcc -pthread -DNDEBUG -O2 -fPIC -I/home/hyperswine/.pyenv/versions/pypy3.9-7.3.10/include/pypy3.9 -c lib/recordclass/_litelist.c -o build/temp.linux-x86_64-3.9/lib/recordclass/_litelist.o
lib/recordclass/_litelist.c: In function ‘litelist_resize’:
lib/recordclass/_litelist.c:31:56: error: ‘PyLiteListObject’ {aka ‘PyListObject’} has no member named ‘ob_item
```

## How to Reproduce

1. From a popos (ubuntu 22.04) environment with pypy 3.9.15, run `pip install Mathics-omnibus`. And get the error in `1`
2. From the same environment, run `pip install Mathics3`. And get the error in `2`

## Expected behavior

Not get stuck at installing build dependencies and not raise an error. I did check the `recordclass` source code, and it seems like the `PyLiteListObject` struct did not in fact contain `ob_item`. Unless Im seeing things, that does seem like a problem with that dependency, so I actually don't know why `Mathics3` works when its including that dep.

## Your Environment

- PopOS 22.04, Intel + Nvidia
- Pypy 3.9.15 through pyenv
- No other mathematica /mathics installs on the system

**Comment by rocky** [comment]
See https://github.com/numba/llvmlite/issues/525

**Comment by davidar** [comment]
It's possible to install the latest master of mathics in pypy now that llvmlite is an optional dependency. It mostly works fine as far as I can tell, though a few tests are failing, and I see some warnings about some builtins failing to load when running the CLI:

```
FAILED test/builtin/numbers/test_calculus.py::test_findminimum[MatchQ[FindMinimum[Cos[x]^2, {x,1.}, Method->brent],{_Real,{x->_Real}}]-True--None] - AssertionError
FAILED test/builtin/numbers/test_calculus.py::test_findminimum[MatchQ[FindMaximum[Cos[x]^2, {x,1.}, Method->brent ], {_Real,{x->_Real}}]-True--None] - AssertionError
FAILED test/builtin/numbers/test_calculus.py::test_findminimum[MatchQ[FindMinimum[Cos[x]^2, {x,1.}, Method->golden],{_Real,{x->_Real}}]-True--None] - AssertionError
FAILED test/builtin/numbers/test_calculus.py::test_findminimum[MatchQ[FindMaximum[Cos[x]^2, {x,1.}, Method->golden ], {_Real,{x->_Real}}]-True--None] - AssertionError
FAILED test/builtin/numbers/test_calculus.py::test_findroot[MatchQ[FindRoot[Cos[x+1.5], {x,.1}, Method->brenth], {x->_Real}]-True-] - AssertionError
FAILED test/builtin/numbers/test_nintegrate.py::test_nintegrate[NIntegrate[1., {x,0,1}, Method->"Quadrature"]-1.-Check that the library is already loaded.-messages0] - AssertionError: expected 0; got 1. Messages: ['The Method option should be a built-in method name in {`Automatic`, `Internal`, `Simpson`}. Using...
FAILED test/builtin/numbers/test_nintegrate.py::test_nintegrate[NIntegrate[1., {x,0,1}, Method->"NotAMethod"]-1.-None-messages1] - AssertionError:  do not match.
FAILED test/test_main.py::test_cli - AssertionError: assert None
```

```
    Not able to load mathics.builtin.scipy_utils.integrators. Check your installation.
    mathics.builtin loads from /home/david/git/mathics-core/mathics/core/load

    Not able to load mathics.builtin.scipy_utils.optimizers. Check your installation.
    mathics.builtin loads from /home/david/git/mathics-core/mathics/core/load
```

**Comment by rocky** [comment]
@davidar I think you are correct that we can reinstate PyPy 3.9 (and other PyPy) now that llvmlite is optional.
