### ISSUE TITLE
failure of Nintegrate for Debye function

### ISSUE THREAD

**Issue by recohen** [Mathics3/mathics-core#67]
Attached is an example.  When run under wolframscript:
wolframscript -file t.wls 210 0.0325 55.85
410.8394779818933
Under mathics:
mathics t.wls 210 0.0325 55.85
Part::partw: Part 2 of {} does not exist.
Part::partw: Part 3 of {} does not exist.
Part::partw: Part 4 of {} does not exist.
Part::partw: Part 2 of {} 
...
FindRoot::nnum: The function value is not a number at TD = 500..
ReplaceAll::reps: FindRoot[msA - const phi[t / TD] / (t / TD) / (M TD), {TD, 500.}] is not a valid replacement rule.
TD /. FindRoot[msA - const phi[t / TD] / (t / TD) / (M TD), {TD, 500.}]

Ron Cohen
[t.wls.zip](https://github.com/Mathics3/mathics-core/files/7534115/t.wls.zip)

**Comment by TiagoCavalcante** [comment]
@recohen `$ScriptCommandLine` is `{}` (even when calling Mathics with arguments). @rocky is that a bug?

**Comment by mmatera** [comment]
First, let's fix some issues in the example.

* The command line to call a script with parameters would be, in mathics,
```
mathics -script t.wls -- 210 0.0325 55.85 410.8394779818933
```
* The script `t.wls` should have semicolons at the end of each line:
```
phi[x_?NumberQ]:=(1/x)*NIntegrate[y/(Exp[y]-1),{y,0,x}];
HBARSI=1.054571800 *10^(-34);KBSI=1.38064852*10^(-23);MPSI=1.672621898*10^(-27);
const=10^(20)*9.*HBARSI^2/KBSI/MPSI;
t=ToExpression[$ScriptCommandLine[[2]]];
msA=ToExpression[$ScriptCommandLine[[3]]];
M=ToExpression[$ScriptCommandLine[[4]]];
td=FindRoot[msA==const/M*(phi[t/TD]/(t/TD))/TD,{TD,500.00000}];
Print[TD/.td]
```

With this, `$ScriptCommandLine` works as it should.

The problem now is that `FindRoot` is not working properly with numeric expressions. This is what we need to solve.

**Comment by mmatera** [comment]
Another problem I just realized is about the `ScriptCommandLine` index. This is another issue to fix.

**Comment by rocky** [comment]
If there is more here, please open a new issue with narrowed information.
