### ISSUE TITLE
Consider replacing lena.tif with a free image

### ISSUE THREAD

**Issue by davide125** [Mathics3/mathics-core#728]
**Is your feature request related to a problem? Please describe.**
Mathics ships a copy of the [Lena test image](https://en.wikipedia.org/wiki/Lenna) under mathics/data/ExampleData/lena.tif. Despite being widely used, this image is non-free and its redistribution is problematic, which complicates packaging Mathics for Linux distributions, among other things.

**Describe the solution you'd like**
Ideally the image would be replaced with a free alternative and the documentation that references it would be adapted.

**Describe alternatives you've considered**
I discovered this while [attempting to package](https://bugzilla.redhat.com/show_bug.cgi?id=2158697) Mathics in Fedora. As stopgap, I can write a shellscript to strip lena.tif from the source tarball, which will unblock packaging, but this solution is suboptimal as the documentation will still reference it, and it requires an additional manual step when updating the package.

**Additional context**
https://github.com/python-pillow/Pillow/issues/884 and https://github.com/matplotlib/matplotlib/pull/1581 discuss how Pillow and matplotlib addressed the issue and presents a few potential alternatives. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=758442 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771191 and [this mailing list thread](https://lists.debian.org/debian-devel/2015/08/msg00090.html) have more details on why the image is not freely distributable and also discuss alternatives.

**Comment by mmatera** [comment]
What about this one?
https://es.wikipedia.org/wiki/Hedy_Lamarr#/media/Archivo:Hedy_Lamarr_in_The_Heavenly_Body_1944.jpg

If B&W is a problem, https://www.publicdomainpictures.net/en/view-image.php?image=15048 is not bad.

**Comment by davide125** [comment]
From a licensing/distribution standpoint, these would both work great.

**Comment by rocky** [comment]
Thanks. If anyone is up for putting in a PR, that would be great.  Probably better to use a color image because examples use that for showing color-related operations.  Also, we use that for showing/testing that TIF images work.

**Comment by rocky** [comment]
> I discovered this while [attempting to package](https://bugzilla.redhat.com/show_bug.cgi?id=2158697) Mathics in Fedora.

Thanks for packaging. BTW, we are in the process of trying to get out another release. I hope it will be done within a few weeks, and we will probably bump version numbers from 5.x to 6.0

**Comment by davide125** [comment]
Looks like this was fixed in #731 so we should be good here. Thanks!
