### ISSUE TITLE
Can mathics-core be used as a library?

### ISSUE THREAD

**Issue by jonaprieto** [Mathics3/mathics-core#829]
As the title says. I'd like to use it on a Jupyter notebook for example?

**Comment by mmatera** [comment]
Sure. 
```
from mathics.session import MathicsSession

session = MathicsSession()

result = session.evaluate("Sin[Pi]").value
```

**Comment by jonaprieto** [comment]
Oh great! Let me try it!

**Comment by mmatera** [comment]
@jonaprieto Is there something else related to this issue, or shall I close it?

**Comment by jonaprieto** [comment]
Thanks, it worked, I forgot to close it myself. ;)
