### ISSUE TITLE
Reference to non-existing file?

### ISSUE THREAD

**Issue by rebcabin** [Mathics3/mathics-core#96]
This issue is something I found just by reading the code. In examples/symbolic_logic/gries_schneider/GS1.m, there is a command to "<<GS0.m", which (according to the prose), brings into existence the symbol "expect" for the internal test framework. 

I'm not equipped to run the examples now (on my iPad), but I don't see how they could run. I'll upload a copy of `GS0.m` from my archives later, if it would be helfpul to do.

**Comment by TiagoCavalcante** [comment]
@rebcabin yes, that file is missing, could you put that file in a PR?

**Comment by rebcabin** [comment]
@TiagoCavalcante Will do when i get back to my computer, possibly today but might not be till Monday.

**Comment by rebcabin** [comment]
PR should show up as issue #97.
