### ISSUE TITLE
Symbol xxx is locked issues.

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-core#971]
## Description

The `$PrintForms` doctest is failing with error message: 

```
ClearAttributes::locked: Symbol True is locked.
```

I suspect this has been happening for a while, but we just haven't been testing it. (Testing may have had a bug that skipped this.)

Similarly when loading CombinatoricaV0.9 we see this: 

```
    SetDelayed: write

    Tag Element in Element[a_List, {index___}] is Protected.
```

## How to Reproduce

In a Mathics3 session

Example 1: 
```
In[1]:= $PrintForms
Out[1]= {TraditionalForm, StandardForm, PythonForm, MathMLForm, SympyForm, FullForm, TeXForm, InputForm}

In[2]:= MemberQ[$PrintForms, MyForm]
Out[2]= False

In[3]:= Format[MyForm[F[x_]]]:= "F<<" <> ToString[x] <> ">>"'
Out[3]= None

In[4]:= Format[F[x_], MyForm]:= MyForm[F[x]]'
Out[4]= None

In[5]:= MemberQ[$PrintForms, MyForm]'
ClearAttributes::locked: Symbol True is locked.
UpSet::write: Tag True in True' is Protected.
...
$RecursionLimit::reclim: Recursion depth of 200 exceeded.
...
```

Example2:
```
In[1]:=  Needs["DiscreteMath`CombinatoricaV0.9`"]

SetDelayed::write: Tag Element in Element[a_List, {index___}] is Protected.
Out[1]= None
```
## Output Given

See output in previous section

## Additional Context

These are small things noticed in going over everything for a release.

**Comment by mmatera** [comment]
@rocky, in the example, the problem seems to be the single quote at the end of lines 3, 4, and 5. Without it, it works as expected. 
The issue seems to be the result of the interaction between `MemberQ` and `Derivative`:
```
In[1]:= MemberQ[$PrintForms, MyForm]'
ClearAttributes::locked: Symbol False is locked.
UpSet::write: Tag False in False' is Protected.
ClearAttributes::locked: Symbol False is locked.
UpSet::write: Tag False in False' is Protected.
ClearAttributes::locked: Symbol False is locked.
UpSet::write: Tag False in False' is Protected.
...
$RecursionLimit::reclim: Recursion depth of 200 exceeded.
Out[1]= $Aborted
```

In any case, this deserves some investigation.

**Comment by rocky** [comment]
Thanks for the information. However, this comes from a real failure I saw, even if my bug reporting is faulty.

Here is revised input and output: 

```
In[1]:= $PrintForms
Out[1]= {StandardForm, SympyForm, MathMLForm, TeXForm, InputForm, TraditionalForm, PythonForm, FullForm}

(*     Suppose now that we want to add a new format 'MyForm'. Initially, it does not belong to '$PrintForms': *)
In[2]:= MemberQ[$PrintForms, MyForm]
Out[2]= False

(*     Now, let's define a format rule: *)
In[3]:= Format[MyForm[F[x_]]]:= "F<<" <> ToString[x] <> ">>"
Out[3]= None

(*     Now, the new format belongs to the '$PrintForms' list *)
In[4]:= MemberQ[$PrintForms, MyForm]
Out[4]= False
```

Above, the

**Comment by mmatera** [comment]
In WMA:
```

In[1]:=  $PrintForms                                                            

Out[1]= {InputForm, OutputForm, TextForm, CForm, FortranForm, ScriptForm, 
 
>    MathMLForm, TeXForm, StandardForm, TraditionalForm}

In[2]:=  MemberQ[$PrintForms, MyForm]                                           

Out[2]= False

In[3]:= Format[MyForm[F[x_]]]:= "F<<" <> ToString[x] <> ">>"                    

In[4]:=  MemberQ[$PrintForms, MyForm]                                           

Out[4]= False

```
 
`In[3]` does not add a `$PrintForm`:  `Format[MyForm[F[x_]]]` does not assign the format `MyForm` to `F` but assigns a general format to `MyForm[...]`. Looking at the definition,
```
In[5]:= ?? F                                                                    

Out[5]= Global`F

In[6]:= ?? MyForm                                                               


FormatType::ftype: Value of option FormatType -> FormatType is not valid.
Out[6]= Global`MyForm
        MakeBoxes[MyForm[F[x_]], FormatType_] ^:= F<<<>ToString[x]<>>>
         
        MyForm[F[x_]] := StringJoin["F<<", ToString[x], ">>"]
```

Notice that this is different than the result of assigning to `Format[expr_,form_]`:

```

In[10]:= Format[G[x_],MyForm]:="G<<"<> ToString[x]<>">>"                        

In[11]:= ?? G                                                                   

Out[11]= Global`G
         G /: G<<x_>> := StringJoin["G<<", ToString[x], ">>"]
          

In[12]:= G[2]                                                                   

Out[12]= G[2]

In[13]:= G[2]//MyForm                                                           

Out[13]//MyForm= MyForm[G[2]]

In[14]:= Format[G[2], MyForm]                                                   

Out[14]= G<<2>>
```

So, Mathics behavior is OK. The bug, on the other hand, is in `Derivative`: In Mathics,
```
In[1]:= False'
ClearAttributes::locked: Symbol False is locked.
UpSet::write: Tag False in False' is Protected.
ClearAttributes::locked: Symbol False is locked.
UpSet::write: Tag False in False' is Protected.
ClearAttributes::locked: Symbol False is locked.
UpSet::write: Tag False in False' is Protected.
...
$RecursionLimit::reclim: Recursion depth of 200 exceeded.
Out[1]= $Aborted
```
while in WMA,
```
In[1]:= False'                                                     

Out[1]= False'
```

**Comment by mmatera** [comment]
This is the rule that produces this weird behaviour with locked symbols:
(mathics/builtin/number/calculus.py:421)

'''
        """Derivative[n__Integer][f_Symbol] /; Module[{t=Sequence@@Slot/@Range[Length[{n}]], result, nothing, ft=f[t]},
            If[Head[ft] === f
            && FreeQ[Join[UpValues[f], DownValues[f], SubValues[f]], Derivative|D]
            && Context[f] != "System`",
                False,
                (* else *)
                ft = f[t];
                Block[{f},
                    Unprotect[f];
                    (*Derivative[1][f] ^= nothing;*)
                    Derivative[n][f] ^= nothing;
                    Derivative[n][nothing] ^= nothing;
                    result = D[ft, Sequence@@Table[{Slot[i], {n}[[i]]}, {i, Length[{n}]}]];
                ];
                FreeQ[result, nothing]
            ]
            ]""": """Module[{t=Sequence@@Slot/@Range[Length[{n}]], result, nothing, ft},
                ft = f[t];
                Block[{f},
                    Unprotect[f];
                    Derivative[n][f] ^= nothing;
                    Derivative[n][nothing] ^= nothing;
                    result = D[ft, Sequence@@Table[{Slot[i], {n}[[i]]}, {i, Length[{n}]}]];
                ];
                Function @@ {result}
            ]""",
'''

This is the kind of things that would be better to codify as a Python method.

**Comment by mmatera** [comment]
Regarding the error message in `Combinatorica.v9`, it is produced by the assignment `Element[a_List,{index___}] := a[[ index ]]` close to the line 971 of the package. The reason is that `Element` is a Builtin symbol, and Combinatorica tries to redefine it. A way to avoid the error would be to make the context explicit or Unprotect it before the assignment.

**Comment by mmatera** [comment]
#974 should fix the issue with Combinatorica
